### ISSUE TITLE
[Bug] Favourites return nulls

### ISSUE THREAD

**Issue by N0D4N** [JustRoxy/ShikimoriSharp#12]
When requesting to `ShikimoriClient.Users.GetFavourites()` returned result is Favorites object with nulls on all properties. I think it's because api client should be requesting to `api/users/id/favourites` as it is written [in api v1 docs](https://shikimori.one/api/doc/1.0/users/favourites) instead of `api/users/id` as it is now.

**Comment by JustRoxy** [comment]
Thanks for your contribution, that was a really interesting bug by me!
