### ISSUE TITLE
Hi, it's me again and I have a question again. Why censored doesn't work?

### ISSUE THREAD

**Issue by Anoxx2020** [JustRoxy/ShikimoriSharp#19]
I have this little piece of code:

 try {
                var animess = await client.Animes.GetAnime(new AnimeRequestSettings
                {

                    order = OrderNow,
                    page = pageNow,
                    limit = 15,
                    kind = Kinder,

                });
                Anime[] ani = animess;
                MessageBox.Show(ani.Length.ToString());
                for (int i = 0; i < 15; i++)
                {
                    AnimeEntity anim = new AnimeEntity();
                    anim.AnimeID = ani[i].Id;
                    anim.StringTextEntity = ani[i].Russian;
                    anim.StringImageEntity = ani[i].Image.Original;
                    anim.HorizontalAlignment = HorizontalAlignment.Center;
                    anim.VerticalAlignment = VerticalAlignment.Center;
                    AnimeList.Items.Add(anim);
                }
                canNextPageCatalog = true;
            }
            catch (Exception ex)
            {
                return;
            }

**Everything works right, but if I add "censored = true"
everything stops working.**

var animess = await client.Animes.GetAnime(new AnimeRequestSettings
                {

                    order = OrderNow,
                    page = pageNow,
                    limit = 15,
                    kind = Kinder,
                    censored = true

                });
There is no error, but the code does not go further than this request. The query itself does not complete.
I need your help.

**Comment by JustRoxy** [comment]
Hi, will take a look tomorrow. If you want you can trace the error by yourself :)

**Comment by Anoxx2020** [comment]
I tried to look, but nothing could be fixed. Can you please check what the
problem is?
Also if it was not difficult could you tell me what the problem was.

сб, 17 дек. 2022 г., 20:34 JustRoxy ***@***.***>:

**Comment by JustRoxy** [comment]
Should be fixed at this version.
You can check the problem solution at PR's commits

https://www.nuget.org/packages/ShikimoriSharp/1.3.4

**Comment by JustRoxy** [comment]
Also thanks for the contribution! :100:
